### ISSUE TITLE
[QUESTION] How to enable/disable engines?

### ISSUE THREAD

**Issue by vanfanel** [diablodiab/libretro-scummvm-backend#1]
Hi @diablodiab 

I am very happy that you did this, because Scummvm games benefit ENORMOUSLY from shaders and RetroArch in general!

Reading the build instructions, I couldn't find any mention to engine enabling/disabling, and looking at the build sources themselves I found that `engines.mk` mentions using the `configure` script to enable/disable engines.
However, the only configure script I see is the upstream scummvm one, that doesn't seem to do anything to the libretro build files.

So, what's the intended method? Manually editing `config.hd`?

Thanks!

**Comment by DrUm78** [comment]
All engines can be enabled/disabled in /build/config.hd, /build/config.hdlite and /build/config.nohd. To disable some, just comment any line with #.

**Comment by vanfanel** [comment]
@DrUm78 Thanks! In the end, if manual enabling is the way to do it, I will use my own custom .config

**Comment by DrUm78** [comment]
That can be set in the Makefile too with NO_HIGH_DEF, LITE or NO_WIP:
https://github.com/diablodiab/libretro-scummvm-backend/blob/cb6918cf0f700d638466ff23c11ed2c057a0e1d1/build/Makefile.common#L14
But this way is less flexible if you want to enable/disable only some of them.

**Comment by vanfanel** [comment]
@DrUm78 Yep, I am passing my own config to the include in Makefile.common
