### ISSUE TITLE
Freeze at exit on many games due to recent ScummVM modification on "quit prompt"

### ISSUE THREAD

**Issue by schmurtzm** [diablodiab/libretro-scummvm-backend#25]
Hi, the modification from [this commit](https://github.com/scummvm/scummvm/commit/c8ba69ed9a15e11b547df0afcf0411f65cfecdaa) has a bad impact on Retroarch exit on many games (probably at least all SCUMM engine games). 

On my device (Miyoo Mini) it freeze on the last image of the game displayed and never quit retroarch. May be it isn't displaying the "quit prompt" and wait for a key to exit which is not mapped on my device ?

A workaround is to modify all the `_messageBannerActive = true;` lines with `false` value (for example [on this line ](https://github.com/scummvm/scummvm/blob/master/engines/scumm/gfx_gui.cpp#L91))

Then Retroarch is able to quit in a normal way again.

**Comment by DrUm78** [comment]
You can also disable the new code [this way](https://github.com/DrUm78/scummvm/commit/6606e6828baacd6c4bddc05496385a178ce7bf66#diff-2fcafec02bc595adbb461884d5b54acf5a5045ab8d6778eeec8dc013c00ba78a).

**Comment by schmurtzm** [comment]
> You can also disable the new code [this way](https://github.com/DrUm78/scummvm/commit/6606e6828baacd6c4bddc05496385a178ce7bf66#diff-2fcafec02bc595adbb461884d5b54acf5a5045ab8d6778eeec8dc013c00ba78a).

Probably a more elegant way, thank you very much :)

**Comment by diablodiab** [comment]
I've adjusted the backend to deal with this without adjusting the scummvm base.

**Comment by DrUm78** [comment]
@diablodiab Does not work for me, I'm still stuck on my handheld console when trying to quit a game, I still need to comment the code this way:
https://github.com/DrUm78/scummvm/commit/21201c215537bb800bb70580c78cb62b374dc1ca#diff-2fcafec02bc595adbb461884d5b54acf5a5045ab8d6778eeec8dc013c00ba78a

**Comment by diablodiab** [comment]
Works when I've tested on MacOS and Android - problem was there before and now no longer.

As an alternative workaround, you can set the following setting in your scummvm.ini for the Scumm engine games:
original_gui=false

**Comment by diablodiab** [comment]
Also, be aware that this change is not on the build bot.

**Comment by DrUm78** [comment]
Only my way worked for me. I have no problem with modifying the upstream as anyway I have to do it for my target device (FunKey S). And I do not use the build bot as I compile myself the Libretro core.

**Comment by spleen1981** [comment]
@diablodiab the workaround in https://github.com/diablodiab/libretro-scummvm-backend/commit/96a63485f3be7888f15cd66215d1e4eaf9d3070b is not guaranteed to work for 2 reasons:
- quit prompt can be localized, if game language is different from english "y" will not work
- if the confirmation key is mapped to any of the retropad controls, it will not work as well

 A better solution is to force `original_gui` setting to `false` in the backend if affected engines are loaded (scumm only afaik), check #30
