### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by ner00** [diablodiab/libretro-scummvm-backend#33]
It's been a while since I've last compiled this repo (~3 months), and currently I'm getting hundreds of `undefined reference` errors resulting in failure.

I'm building in Linux, for Windows, and the environment is exactly the same as before; I have no clue on how to resolve these errors.

Any idea?

Attached errors from the console: [libretro-scummvm-backend_build-errors.txt](https://github.com/diablodiab/libretro-scummvm-backend/files/10304741/libretro-scummvm-backend_build-errors.txt)

**Comment by diablodiab** [comment]
Could you try this repo instead?
https://github.com/diablodiab/scummvm-libretro-backend

**Comment by ner00** [comment]
This other repo builds fine. What's the difference between both? Should I just stick with that one then and just ignore the `libretro-scummvm` one? Or should I somehow try to fix the missing dependencies?

**Comment by diablodiab** [comment]
That other repo is/was intended to be handed over to the Libretro team.

**Comment by ner00** [comment]
> That other repo is/was intended to be handed over to the Libretro team.

I remember a discussion about that with someone from libretro. But my question still stands, what's the big difference since the other and this one?

I'm asking because I wanted to know if there are any known drawbacks, besides the fact that I can't compile this one at all which by default would make me stick with the second one.

**Comment by diablodiab** [comment]
It's identical to the old repo except that I've fixed compilation errors
